location /numbering/api/ {
    proxy_pass http://localhost:32451/api/;
}
location /numbering/ {
    alias /home/richia/arigi.top/app/numbering/frontend/dist/;
    index index.html;
}
location /numberheaven/ {
    return 301 /numbering/;
}
